---
- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 300
    
- name: install packages
  apt: pkg={{ item }} state=present
  with_items:
    - nano
    - curl
    - git
    - screen
    - sudo
    - wget
    - mlocate