---
- name: create required directories for sabnzbd
  file: path="{{ item }}" state=directory mode=755
  with_items:
    - /opt/appdata/sabnzbd/config
    - /mnt/storage/download/complete
    - /mnt/storage/download/incomplete

- name: install python-setuptools
  apt:
    name: python-setuptools
    state: present
    update_cache: yes
    
- name: install pip
  easy_install:
    name: pip
    
- name: install docker-py via pip
  pip:
    name: docker-py
    state: present

- name: create sabnzbd docker container
  docker:
    name: sabnzbd
    image: linuxserver/sabnzbd
    state: running
    docker_api_version: 1.18
    ports:
    - 8080:8080
    volumes:
    - /opt/appdata/sabnzbd/config:/config
    - /mnt/storage/download/complete:/download/complete
    - /mnt/storage/download/incomplete:/download/incomplete