---
- name: switch debian repositories from stable to testing
  apt_repository: repo="{{ item }}" state=absent
  with_items:
    - deb http://ftp.us.debian.org/debian/ jessie main
    - deb-src http://ftp.us.debian.org/debian/ jessie main
    - deb http://security.debian.org/ jessie/updates main
    - deb-src http://security.debian.org/ jessie/updates main
    - deb http://ftp.us.debian.org/debian/ jessie-updates main
    - deb-src http://ftp.us.debian.org/debian/ jessie-updates main
  
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - deb http://ftp.us.debian.org/debian/ testing main
    - deb-src http://ftp.us.debian.org/debian/ testing main
    - deb http://security.debian.org/ testing/updates main
    - deb-src http://security.debian.org/ testing/updates main
    - deb http://ftp.us.debian.org/debian/ testing-updates main
    - deb-src http://ftp.us.debian.org/debian/ testing-updates main
    
- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 300
    
- name: install packages
  apt: pkg={{ item }} state=present
  with_items:
    - nano
    - curl
    - git
    - screen
    - sudo
    - wget
    - mlocate