---
- name: copy new sources.list for testing distro repo
  copy:
    src: etc/apt/sources.list
    dest: /etc/apt/sources.list
    
- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: dist
    
# - name: install packages
  # apt: pkg={{ item }} state=present
  # with_items:
    # - nano
    # - curl
    # - git
    # - screen
    # - sudo
    # - wget
    # - mlocate