---
- name: install docker dependency packages
  apt: name="{{ item }}" state=present
  with_items: docker_dependencies

- name: install docker gpg key for apt
  apt_key:
    keyserver: ha.pool.sks-keyservers.net
    id: 58118E89F3A912897C070ADBF76221572C52609D
