---
- name: install docker dependency packages
  apt: name="{{ item }}" state=present
  with_items: docker_dependencies

- name: install docker gpg key for apt
  apt_key:
    keyserver: "{{ docker_keyserver }}"
    id: "{{ docker_key_id }}"

- name: install docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present