---
- name: install docker dependency packages
  apt:
    name: "{{ item }}"
    status: present
    update_cache: yes
    #with_items: "{{ docker_dependencies }}"
    with_items: 
      - apt-transport-https
      - ca-certificates
      - gnupg2